---
# SPDX-FileCopyrightText: 2022 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: MIT
branches:
    - main
    - name: next
      prerelease: true
plugins:
    - '@semantic-release/commit-analyzer'
    - '@semantic-release/release-notes-generator'
    - - '@semantic-release/exec'
      - prepareCmd: 'pnpm run format'
    - '@semantic-release/changelog'
    - - '@semantic-release/npm'
      - npmPublish: false
    - - '@semantic-release/git'
      - assets: ['CHANGELOG.md', 'package.json', 'package-lock.json']
        message: 'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}'
    - '@semantic-release/github'
