---
extends: default
ignore: |
    node_modules/
    pnpm-lock.yaml
rules:
    line-length:
        max: 150
    document-start: disable
    truthy:
        check-keys: false
    comments:
        min-spaces-from-content: 1
    braces:
        max-spaces-inside: 1
    indentation:
        spaces: 4
        indent-sequences: true
