extends: default

ignore: |
  node_modules/
  *-lock.yaml

rules:
  line-length:
    max: 160
  document-start: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
