blank_issues_enabled: false
contact_links:
    - name: 💬 GitHub Discussions
      url: https://github.com/aimami/banned_books_jeopardy/discussions
      about: Ask questions and discuss ideas with the community
    - name: 🔒 Security Vulnerability
      url: https://github.com/aimami/banned_books_jeopardy/security/advisories/new
      about: Report a security vulnerability privately
