entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'

api:
  insecure: true

providers:
  docker:
    exposedByDefault: false

tls:
  certificates:
    - certFile: /Users/aimami/.ssl_certs/_wildcard.dev.localhost+1.pem
      keyFile: /Users/aimami/.ssl_certs/_wildcard.dev.localhost+1-key.pem

log:
  level: INFO
  format: common

accessLog:
  filePath: 'logs/traefik-access.log'
